# Generated by Django 5.2.5 on 2025-08-22 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_order_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='products',
        ),
    ]
